version: '3.8'

services:
  db:
    image: postgres:15
    container_name: fintrack-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '0402'
      POSTGRES_DB: fintrack
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fintrack"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fintrack-network

  redis:
    image: redis:7.0-alpine
    container_name: fintrack-redis
    ports:
      - "6379:6379"
    networks:
      - fintrack-network

  app:
    build: .
    container_name: fintrack-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: fintrack
      DB_USERNAME: postgres
      DB_PASSWORD: '0402'
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - fintrack-network

# This must be at the very bottom, aligned to the far left
networks:
  fintrack-network:
    driver: bridge

volumes:
  postgres_data: